//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5_UP0101
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Airline_sales_DepartmentEntities3 : DbContext
    {
        public Airline_sales_DepartmentEntities3()
            : base("name=Airline_sales_DepartmentEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Airports> Airports { get; set; }
        public virtual DbSet<Baggage_type> Baggage_type { get; set; }
        public virtual DbSet<CLASSS> CLASSS { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Companies_carrier> Companies_carrier { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Flights> Flights { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<Towns> Towns { get; set; }
        public virtual DbSet<User_Roles> User_Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Waiting_hall> Waiting_hall { get; set; }
    }
}
