//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5_UP0101
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tickets()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int TicketID { get; set; }
        public Nullable<int> FlightID { get; set; }
        public Nullable<int> CLASSSID { get; set; }
        public Nullable<int> Baggage_typeID { get; set; }
        public Nullable<int> Waiting_hallID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public decimal Price { get; set; }
        public string Animails { get; set; }
        public string Eat { get; set; }
    
        public virtual Baggage_type Baggage_type { get; set; }
        public virtual CLASSS CLASSS { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Flights Flights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Waiting_hall Waiting_hall { get; set; }
    }
}
